#!/usr/bin/env node
/**
 * generate-env.js
 * Reads .env and writes js/env.js exposing only PUBLIC_* vars to the browser.
 * Run via: npm run generate-env  (or npm run build)
 */
const fs = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '..', '.env');
const outPath = path.resolve(__dirname, '..', 'js', 'env.js');

if (!fs.existsSync(envPath)) {
  console.error('[generate-env] No .env file found. Copy .env.example to .env and fill in values.');
  process.exit(1);
}

const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
const publicVars = {};

// DENYLIST: Server-only secrets that must NEVER reach the browser
const DENIED_KEYS = new Set([
  'SUPABASE_SECRET_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'NOMOD_HOSTED_CHECKOUT_API_KEY',
  'NOMAD_API_KEY',
  'NOMOD_WEBHOOK_SECRET',
  'NOMAD_WEBHOOK_SECRET',
  'SETUP_ADMIN_SECRET',
  'RESEND_API_KEY',
  'EMAIL_FROM',
  'GITHUB_API',
]);

for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eqIdx = trimmed.indexOf('=');
  if (eqIdx === -1) continue;
  const key = trimmed.substring(0, eqIdx).trim();
  const value = trimmed.substring(eqIdx + 1).trim();
  if (DENIED_KEYS.has(key)) {
    console.warn(`[generate-env] BLOCKED server secret from env.js: ${key}`);
    continue;
  }
  if (key.startsWith('PUBLIC_')) {
    publicVars[key] = value;
  }
}

// Ensure js directory exists
const jsDir = path.resolve(__dirname, '..', 'js');
if (!fs.existsSync(jsDir)) {
  fs.mkdirSync(jsDir, { recursive: true });
}

const content = `// Auto-generated by scripts/generate-env.js — DO NOT EDIT
// Only PUBLIC_* env vars are exposed here. Server secrets stay in process.env.
window.__ENV = ${JSON.stringify(publicVars, null, 2)};
`;

fs.writeFileSync(outPath, content, 'utf-8');
console.log(`[generate-env] Wrote ${Object.keys(publicVars).length} public vars to js/env.js`);
