#!/usr/bin/env node
/**
 * generate-env.js
 * Reads PUBLIC_* variables from the environment (and optionally a local
 * .env file) and writes js/env.js for the browser.
 *
 * Hostinger mode: production env vars are injected by the platform into
 * process.env — there is no .env file. This script therefore always merges
 * process.env and never fails when .env is absent (so `npm start` can run
 * on Hostinger). If neither source provides PUBLIC_* vars it writes an
 * empty js/env.js and warns instead of crashing the boot.
 *
 * SECURITY: only PUBLIC_* variables are ever written. Server secrets are
 * denylisted and can never reach the browser.
 */
const fs = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '..', '.env');
const outPath = path.resolve(__dirname, '..', 'js', 'env.js');

// DENYLIST: Server-only secrets that must NEVER reach the browser
const DENIED_KEYS = new Set([
  'SUPABASE_SECRET_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'NOMOD_HOSTED_CHECKOUT_API_KEY',
  'NOMAD_API_KEY',
  'NOMOD_WEBHOOK_SECRET',
  'NOMAD_WEBHOOK_SECRET',
  'SETUP_ADMIN_SECRET',
  'RESEND_API_KEY',
  'EMAIL_FROM',
  'GITHUB_API',
]);

const publicVars = {};

// ── 1) Local .env file (dev only). Values are overridden by process.env. ──
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.substring(0, eqIdx).trim();
    const value = trimmed.substring(eqIdx + 1).trim();
    if (DENIED_KEYS.has(key)) {
      console.warn(`[generate-env] BLOCKED server secret from env.js: ${key}`);
      continue;
    }
    if (key.startsWith('PUBLIC_')) publicVars[key] = value;
  }
} else {
  console.log('[generate-env] No .env file — using environment variables only (Hostinger mode).');
}

// ── 2) process.env (Hostinger / production) — overrides .env values ──
for (const [key, value] of Object.entries(process.env)) {
  if (value === undefined || value === '') continue;
  if (DENIED_KEYS.has(key)) continue; // belt-and-braces: never from env either
  if (key.startsWith('PUBLIC_')) publicVars[key] = value;
}

// ── Write js/env.js ──
const jsDir = path.resolve(__dirname, '..', 'js');
if (!fs.existsSync(jsDir)) {
  fs.mkdirSync(jsDir, { recursive: true });
}

const count = Object.keys(publicVars).length;
if (count === 0) {
  console.warn('[generate-env] WARNING: no PUBLIC_* variables found (.env missing and none in environment).');
  console.warn('[generate-env] On Hostinger, add PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_PUBLISHABLE_KEY and PUBLIC_SITE_URL.');
} else {
  console.log(`[generate-env] Found ${count} public var(s).`);
}

const content = `// Auto-generated by scripts/generate-env.js — DO NOT EDIT
// Only PUBLIC_* env vars are exposed here. Server secrets stay in process.env.
window.__ENV = ${JSON.stringify(publicVars, null, 2)};
`;

fs.writeFileSync(outPath, content, 'utf-8');
console.log(`[generate-env] Wrote ${count} public vars to js/env.js`);
